description: Dokumentation is a minimal ~1.1 kB (minified and gzipped) CSS framework with documentation in mind.
show_downloads: true
github:
  repository_url: https://github.com/tobiasroeder/Dokumentation
  zip_url: https://github.com/tobiasroeder/Dokumentation/zipball/master
  tar_url: https://github.com/tobiasroeder/Dokumentation/tarball/master
